DROP TABLE "SOPAADMIN"."TBSOPTCVSTAG" CASCADE CONSTRAINTS;

CREATE TABLE "SOPAADMIN"."TBSOPTCVSTAG"
  (
    "M_SID"   NUMBER(10,0) NOT NULL,
    "VERSION" VARCHAR2(20 BYTE) NOT NULL,
    "TAGNAME" VARCHAR2(100 BYTE) NOT NULL,
    "CREATOR" VARCHAR2(50 BYTE),
    "CREATETIME" TIMESTAMP (6),
    "MODIFIER" VARCHAR2(50 BYTE),
    "LASTUPDATE" TIMESTAMP (6),
    CONSTRAINT "TBSOPTCVSTAG_PK" PRIMARY KEY ("M_SID", "VERSION", "TAGNAME") USING INDEX TABLESPACE "SOPA_INDEX",
    CONSTRAINT "TBSOPTCVSTAG_TBSOPTCVSVER_FK" FOREIGN KEY ("M_SID", "VERSION") REFERENCES "SOPAADMIN"."TBSOPTCVSVER" ("M_SID", "VERSION") ON DELETE SET NULL ENABLE
  ) TABLESPACE "SOPA_DATA" ;