package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 7:17:59 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * TbsoptcvstagId generated by hbm2java
 */
public class TbsoptcvstagId implements java.io.Serializable {

	private Long MSid;
	private BigDecimal version;
	private String tagname;

	public TbsoptcvstagId() {
	}

	public TbsoptcvstagId(Long MSid, BigDecimal version, String tagname) {
		this.MSid = MSid;
		this.version = version;
		this.tagname = tagname;
	}

	public Long getMSid() {
		return this.MSid;
	}

	public void setMSid(Long MSid) {
		this.MSid = MSid;
	}

	public BigDecimal getVersion() {
		return this.version;
	}

	public void setVersion(BigDecimal version) {
		this.version = version;
	}

	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbsoptcvstagId))
			return false;
		TbsoptcvstagId castOther = (TbsoptcvstagId) other;

		return ((this.getMSid() == castOther.getMSid()) || (this.getMSid() != null
				&& castOther.getMSid() != null && this.getMSid().equals(
				castOther.getMSid())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion()
						.equals(castOther.getVersion())))
				&& ((this.getTagname() == castOther.getTagname()) || (this
						.getTagname() != null
						&& castOther.getTagname() != null && this.getTagname()
						.equals(castOther.getTagname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMSid() == null ? 0 : this.getMSid().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getTagname() == null ? 0 : this.getTagname().hashCode());
		return result;
	}

}
