package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 7:17:59 PM by Hibernate Tools 3.3.0.GA

import java.sql.Timestamp;

/**
 * Tbsoptcvslogin generated by hbm2java
 */
public class Tbsoptcvslogin implements java.io.Serializable {

	private Long sid;
	private char flag;
	private char status;
	private String description;
	private String creator;
	private Timestamp createtime;
	private String modifier;
	private Timestamp lastupdate;

	public Tbsoptcvslogin() {
	}

	public Tbsoptcvslogin(Long sid, char flag, char status, String description) {
		this.sid = sid;
		this.flag = flag;
		this.status = status;
		this.description = description;
	}

	public Tbsoptcvslogin(Long sid, char flag, char status, String description,
			String creator, Timestamp createtime, String modifier,
			Timestamp lastupdate) {
		this.sid = sid;
		this.flag = flag;
		this.status = status;
		this.description = description;
		this.creator = creator;
		this.createtime = createtime;
		this.modifier = modifier;
		this.lastupdate = lastupdate;
	}

	public Long getSid() {
		return this.sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}

	public char getFlag() {
		return this.flag;
	}

	public void setFlag(char flag) {
		this.flag = flag;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Timestamp getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}

}
