package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 8:16:51 PM by Hibernate Tools 3.3.0.GA

/**
 * TbsoptcvstagId generated by hbm2java
 */
public class TbsoptcvstagId implements java.io.Serializable {

	private Tbsoptcvsver tbsoptcvsver;
	private String tagname;

	public TbsoptcvstagId() {
	}

	public TbsoptcvstagId(Tbsoptcvsver tbsoptcvsver, String tagname) {
		this.tbsoptcvsver = tbsoptcvsver;
		this.tagname = tagname;
	}

	public Tbsoptcvsver getTbsoptcvsver() {
		return this.tbsoptcvsver;
	}

	public void setTbsoptcvsver(Tbsoptcvsver tbsoptcvsver) {
		this.tbsoptcvsver = tbsoptcvsver;
	}

	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbsoptcvstagId))
			return false;
		TbsoptcvstagId castOther = (TbsoptcvstagId) other;

		return ((this.getTbsoptcvsver() == castOther.getTbsoptcvsver()) || (this
				.getTbsoptcvsver() != null
				&& castOther.getTbsoptcvsver() != null && this
				.getTbsoptcvsver().equals(castOther.getTbsoptcvsver())))
				&& ((this.getTagname() == castOther.getTagname()) || (this
						.getTagname() != null
						&& castOther.getTagname() != null && this.getTagname()
						.equals(castOther.getTagname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTbsoptcvsver() == null ? 0 : this.getTbsoptcvsver()
						.hashCode());
		result = 37 * result
				+ (getTagname() == null ? 0 : this.getTagname().hashCode());
		return result;
	}

}
