package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 7:17:59 PM by Hibernate Tools 3.3.0.GA

import java.sql.Timestamp;

/**
 * Tbsoptcvstag generated by hbm2java
 */
public class Tbsoptcvstag implements java.io.Serializable {

	private TbsoptcvstagId id;
	private Tbsoptcvsver tbsoptcvsver;
	private String creator;
	private Timestamp createtime;
	private String modifier;
	private Timestamp lastupdate;

	public Tbsoptcvstag() {
	}

	public Tbsoptcvstag(TbsoptcvstagId id, Tbsoptcvsver tbsoptcvsver) {
		this.id = id;
		this.tbsoptcvsver = tbsoptcvsver;
	}

	public Tbsoptcvstag(TbsoptcvstagId id, Tbsoptcvsver tbsoptcvsver,
			String creator, Timestamp createtime, String modifier,
			Timestamp lastupdate) {
		this.id = id;
		this.tbsoptcvsver = tbsoptcvsver;
		this.creator = creator;
		this.createtime = createtime;
		this.modifier = modifier;
		this.lastupdate = lastupdate;
	}

	public TbsoptcvstagId getId() {
		return this.id;
	}

	public void setId(TbsoptcvstagId id) {
		this.id = id;
	}

	public Tbsoptcvsver getTbsoptcvsver() {
		return this.tbsoptcvsver;
	}

	public void setTbsoptcvsver(Tbsoptcvsver tbsoptcvsver) {
		this.tbsoptcvsver = tbsoptcvsver;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Timestamp getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}

}
