package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 8:16:51 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbsoptcvsmap generated by hbm2java
 */
public class Tbsoptcvsmap implements java.io.Serializable {

	private Long MSid;
	private String rcsfile;
	private String filename;
	private String programid;
	private String module;
	private Character clientserver;
	private BigDecimal versionhead;
	private String creator;
	private Timestamp createtime;
	private String modifier;
	private Timestamp lastupdate;
	private Set tbsoptcvsvers = new HashSet(0);

	public Tbsoptcvsmap() {
	}

	public Tbsoptcvsmap(Long MSid, String rcsfile, String filename,
			BigDecimal versionhead) {
		this.MSid = MSid;
		this.rcsfile = rcsfile;
		this.filename = filename;
		this.versionhead = versionhead;
	}

	public Tbsoptcvsmap(Long MSid, String rcsfile, String filename,
			String programid, String module, Character clientserver,
			BigDecimal versionhead, String creator, Timestamp createtime,
			String modifier, Timestamp lastupdate, Set tbsoptcvsvers) {
		this.MSid = MSid;
		this.rcsfile = rcsfile;
		this.filename = filename;
		this.programid = programid;
		this.module = module;
		this.clientserver = clientserver;
		this.versionhead = versionhead;
		this.creator = creator;
		this.createtime = createtime;
		this.modifier = modifier;
		this.lastupdate = lastupdate;
		this.tbsoptcvsvers = tbsoptcvsvers;
	}

	public Long getMSid() {
		return this.MSid;
	}

	public void setMSid(Long MSid) {
		this.MSid = MSid;
	}

	public String getRcsfile() {
		return this.rcsfile;
	}

	public void setRcsfile(String rcsfile) {
		this.rcsfile = rcsfile;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getProgramid() {
		return this.programid;
	}

	public void setProgramid(String programid) {
		this.programid = programid;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public Character getClientserver() {
		return this.clientserver;
	}

	public void setClientserver(Character clientserver) {
		this.clientserver = clientserver;
	}

	public BigDecimal getVersionhead() {
		return this.versionhead;
	}

	public void setVersionhead(BigDecimal versionhead) {
		this.versionhead = versionhead;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Timestamp getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Set getTbsoptcvsvers() {
		return this.tbsoptcvsvers;
	}

	public void setTbsoptcvsvers(Set tbsoptcvsvers) {
		this.tbsoptcvsvers = tbsoptcvsvers;
	}

}
