package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 7:17:59 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * TbsoptcvsverId generated by hbm2java
 */
public class TbsoptcvsverId implements java.io.Serializable {

	private long MSid;
	private BigDecimal version;

	public TbsoptcvsverId() {
	}

	public TbsoptcvsverId(long MSid, BigDecimal version) {
		this.MSid = MSid;
		this.version = version;
	}

	public long getMSid() {
		return this.MSid;
	}

	public void setMSid(long MSid) {
		this.MSid = MSid;
	}

	public BigDecimal getVersion() {
		return this.version;
	}

	public void setVersion(BigDecimal version) {
		this.version = version;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbsoptcvsverId))
			return false;
		TbsoptcvsverId castOther = (TbsoptcvsverId) other;

		return (this.getMSid() == castOther.getMSid())
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion()
						.equals(castOther.getVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMSid();
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		return result;
	}

}
