package com.systex.sop.cvs.dto;

// Generated Jan 10, 2012 7:17:59 PM by Hibernate Tools 3.3.0.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbsoptcvsver generated by hbm2java
 */
public class Tbsoptcvsver implements java.io.Serializable {

	private TbsoptcvsverId id;
	private Tbsoptcvsmap tbsoptcvsmap;
	private String author;
	private Timestamp verdate;
	private char state;
	private String fulldesc;
	private String descId;
	private String descDesc;
	private String descStep;
	private String creator;
	private Timestamp createtime;
	private String modifier;
	private Timestamp lastupdate;
	private Set tbsoptcvstags = new HashSet(0);

	public Tbsoptcvsver() {
	}

	public Tbsoptcvsver(TbsoptcvsverId id, Tbsoptcvsmap tbsoptcvsmap,
			String author, Timestamp verdate, char state) {
		this.id = id;
		this.tbsoptcvsmap = tbsoptcvsmap;
		this.author = author;
		this.verdate = verdate;
		this.state = state;
	}

	public Tbsoptcvsver(TbsoptcvsverId id, Tbsoptcvsmap tbsoptcvsmap,
			String author, Timestamp verdate, char state, String fulldesc,
			String descId, String descDesc, String descStep, String creator,
			Timestamp createtime, String modifier, Timestamp lastupdate,
			Set tbsoptcvstags) {
		this.id = id;
		this.tbsoptcvsmap = tbsoptcvsmap;
		this.author = author;
		this.verdate = verdate;
		this.state = state;
		this.fulldesc = fulldesc;
		this.descId = descId;
		this.descDesc = descDesc;
		this.descStep = descStep;
		this.creator = creator;
		this.createtime = createtime;
		this.modifier = modifier;
		this.lastupdate = lastupdate;
		this.tbsoptcvstags = tbsoptcvstags;
	}

	public TbsoptcvsverId getId() {
		return this.id;
	}

	public void setId(TbsoptcvsverId id) {
		this.id = id;
	}

	public Tbsoptcvsmap getTbsoptcvsmap() {
		return this.tbsoptcvsmap;
	}

	public void setTbsoptcvsmap(Tbsoptcvsmap tbsoptcvsmap) {
		this.tbsoptcvsmap = tbsoptcvsmap;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Timestamp getVerdate() {
		return this.verdate;
	}

	public void setVerdate(Timestamp verdate) {
		this.verdate = verdate;
	}

	public char getState() {
		return this.state;
	}

	public void setState(char state) {
		this.state = state;
	}

	public String getFulldesc() {
		return this.fulldesc;
	}

	public void setFulldesc(String fulldesc) {
		this.fulldesc = fulldesc;
	}

	public String getDescId() {
		return this.descId;
	}

	public void setDescId(String descId) {
		this.descId = descId;
	}

	public String getDescDesc() {
		return this.descDesc;
	}

	public void setDescDesc(String descDesc) {
		this.descDesc = descDesc;
	}

	public String getDescStep() {
		return this.descStep;
	}

	public void setDescStep(String descStep) {
		this.descStep = descStep;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Timestamp getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Set getTbsoptcvstags() {
		return this.tbsoptcvstags;
	}

	public void setTbsoptcvstags(Set tbsoptcvstags) {
		this.tbsoptcvstags = tbsoptcvstags;
	}

}
