DROP TABLE "SOPAADMIN"."TBSOPTCVSVER" CASCADE CONSTRAINTS;

CREATE TABLE "SOPAADMIN"."TBSOPTCVSVER"
  (
    "M_SID"      NUMBER(10,0) NOT NULL,
    "VERSION"    VARCHAR2(20 BYTE) NOT NULL,
    "AUTHOR"     VARCHAR2(50 BYTE) NOT NULL,
    "VERDATE"    TIMESTAMP (6) NOT NULL,
    "STATE"      CHAR(1 BYTE) NOT NULL,
    "FULLDESC"   VARCHAR2(4000 BYTE),
    "DESC_ID"    VARCHAR2(50 BYTE),
    "DESC_DESC"  VARCHAR2(3000 BYTE),
    "DESC_STEP"  VARCHAR2(3000 BYTE),
    "CREATOR"    VARCHAR2(50 BYTE),
    "CREATETIME" TIMESTAMP (6),
    "MODIFIER"   VARCHAR2(50 BYTE),
    "LASTUPDATE" TIMESTAMP (6),
    CONSTRAINT "TBSOPTCVSVER_PK" PRIMARY KEY ("M_SID", "VERSION") USING INDEX TABLESPACE "SOPA_INDEX",
    CONSTRAINT "TBSOPTCVSVER_TBSOPTCVSMAP_FK" FOREIGN KEY ("M_SID") REFERENCES "SOPAADMIN"."TBSOPTCVSMAP" ("M_SID") ON DELETE SET NULL ENABLE
  ) TABLESPACE "SOPA_DATA";