DROP TABLE "SOPAADMIN"."TBSOPTCVSTAG" CASCADE CONSTRAINTS;

CREATE TABLE "SOPAADMIN"."TBSOPTCVSTAG"
  (
    "M_SID"   NUMBER(10,0) NOT NULL,
    "VERSION" VARCHAR2(20 BYTE) NOT NULL,
    "TAGNAME" VARCHAR2(100 BYTE) NOT NULL,
    CONSTRAINT "TBSOPTCVSTAG_TBSOPTCVSVER_FK" FOREIGN KEY ("M_SID", "VERSION") REFERENCES "SOPAADMIN"."TBSOPTCVSVER" ("M_SID", "VERSION") ON DELETE SET NULL ENABLE
  ) TABLESPACE "SOPA_DATA" ;